[project]
name = "neteasemusicconverter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "mutagen>=1.47.0",
    "pillow==12.0.0",
    "pycryptodome==3.23.0",
    "pyside6>=6.10.1",
]
