[project]
name = "neteasemusicconverter"
version = "1.1.0"
description = "A tool for .ncm file decryption."
requires-python = ">=3.14"
dependencies = [
    "mutagen>=1.47.0",
    "pillow==12.0.0",
    "pycryptodome==3.23.0",
    "pyinstaller==6.17.0",
    "pyside6>=6.10.1",
]
